version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/src/Api"
      - "/src/Blazor"
      - "/Application"
      - "/Domain"
      - "/Infrastructure"
      - "/Tests"
      - "/_build"
    schedule:
      interval: "weekly"
