name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Restore projects
        run: dotnet restore

      - name: Build projects
        run: dotnet build --no-restore

      - name: Generate metadata
        run: dotnet tool run docfx metadata ./documentation/docfx.json

      - name: Build DocFX
        run: dotnet tool run docfx build ./documentation/docfx.json

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get ID token
        uses: actions/github-script@v7.0.1
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      - name: Build and deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_MOSS_03728DF03 }}
          action: "upload"
          app_location: "documentation/_site"
          api_location: ""
          output_location: "documentation/_site"
          github_id_token: ${{ steps.idtoken.outputs.result }}
          skip_app_build: true
