name: Build application

on:
  workflow_dispatch:
    inputs:
      run-self-hosted-macos:
        description: Run build on a self-hosted MacOS environment
        required: false
        default: false
        type: boolean

permissions: read-all

jobs:

    build-application-macos:
      name: Build the appplication on MacOS
      runs-on: [self-hosted, macOS]

      steps:
      
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Print repository data
        run: ./build.sh PrintRepositoryData

      - name: Print version data
        run: ./build.sh PrintVersionData

      - name: Restore .NET tools
        run: ./build.sh RestoreTools

      - name: Restore projects
        run: ./build.sh Restore

      - name: Build application
        run: ./build.sh Compile

      - name: Create database
        run: ./build.sh UpdateDatabase --EfProjectPath "src/ApplicationApi/ApplicationApi.csproj"
