name: Build application

on:
  push:
      branches: [ master ]

permissions: read-all

jobs:
    build-application:
        name: Build the appplication
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ ubuntu-latest, windows-latest ]

        steps:

        - name: Harden runner
          uses: step-security/harden-runner@v2.13.1 # v2.13.1
          with:
            egress-policy: audit

        - name: Checkout repository
          uses: actions/checkout@v5.0.0 # v5.0.0

        - name: Setup .NET
          uses: actions/setup-dotnet@v5.0.0 # v5.0.0
          with:
            dotnet-version: 9.0.x

        - name: Print repository data
          run: ./build.sh PrintRepositoryData

        - name: Print version data
          run: ./build.sh PrintVersionData

        - name: Restore .NET tools
          run: ./build.sh RestoreTools

        - name: Restore projects
          run: ./build.sh Restore

        - name: Build application
          run: ./build.sh Compile

        - name: Create database
          run: ./build.sh UpdateDatabase --EfProjectPath "src/ApplicationApi/ApplicationApi.csproj"
