name: Build application

on:
  push:
      branches: [ master ]

permissions: read-all

jobs:
    build-application:
        name: Build the appplication
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ ubuntu-latest, windows-latest ]

        steps:

        - name: Harden runner
          uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
          with:
            egress-policy: audit

        - name: Checkout repository
          uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

        - name: Setup .NET 9 SDK
          uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
          with:
            dotnet-version: 9.x

        - name: Print repository data
          run: ./build.sh PrintRepositoryData

        - name: Print version data
          run: ./build.sh PrintVersionData

        - name: Restore .NET tools
          run: ./build.sh RestoreTools

        - name: Restore projects
          run: ./build.sh Restore

        - name: Build application
          run: ./build.sh Compile

        - name: Create database
          run: ./build.sh UpdateDatabase --EfProjectPath "src/ApplicationApi/ApplicationApi.csproj"
