name: Build and publish Docker image

on:
  push:
    branches: [ "master" ]

permissions: read-all

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
              
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        id: build-frontend
        uses: docker/build-push-action@v6
        with:
          context: ./src/Blazor
          file: ./src/Blazor/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/application-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push backend
        id: build-backend
        uses: docker/build-push-action@v6
        with:
          context: ./src/Api
          file: ./src/Api/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/application-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign Blazor frontend
        run: cosign sign --yes ghcr.io/${{ github.repository_owner }}/application-frontend:latest

      - name: Sign API backend
        run: cosign sign --yes ghcr.io/${{ github.repository_owner }}/application-backend:latest
