name: Print repository information

on:
  workflow_dispatch:
    inputs:
      repository-information-type:
        description: Type of repository information to print - basic or extended
        required: true
        default: basic
        type: choice
        options: [ basic, extended ]
  push:
    branches: [ master ]

permissions: read-all

jobs:
    print-repository-information:
        runs-on: ubuntu-latest
        steps:
            - name: Harden runner
              uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
              with:
                egress-policy: audit

            - name: Checkout code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - name: Install actions core npm package
              run: npm install @actions/core

            - name: Install actions github npm package
              run: npm install @actions/github

            - name: Print repository information
              uses: ./.github/workflows/actions/print-repository-information
              with:
                repository-information-type: ${{ github.event.inputs.repository-information-type }}

