name: GitHub Actions Version Updater

on:
  workflow_dispatch:
  schedule:
    - cron:  0 0 * * 0 # At 00:00 on Sunday

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure workflow secret is configured
        run: |
          if [ -z "${{ secrets.WORKFLOW_SECRET }}" ]; then
            echo "::error::The WORKFLOW_SECRET secret is not configured in the repository's secrets."
            echo "::error::The WORKFLOW_SECRET secret should be a copy of a PAT token."
            
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@d8781caf11d11168579c8e5e94f62b068038f442 # v0.9.0
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}
          