name: I test my action

on: [push]

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Hello
              id: say-hello
              uses: ./.github/workflows/actions/test
