// <auto-generated />
using System;
using Infrastructure.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018181552_UpdatePopulationRecordsCreatedAtConversion")]
    partial class UpdatePopulationRecordsCreatedAtConversion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Domain.Entities.PopulationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Created at");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PopulationRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
