// <auto-generated />
using System;
using Infrastructure.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018202648_RemovePopulationPropertyFromPopulationRecord")]
    partial class RemovePopulationPropertyFromPopulationRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Domain.Entities.Population", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Created at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Populations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PopulationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Created at");

                    b.Property<Guid>("PopulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PopulationSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PopulationId");

                    b.ToTable("PopulationRecords", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PopulationRecord", b =>
                {
                    b.HasOne("Domain.Entities.Population", null)
                        .WithMany("PopulationRecords")
                        .HasForeignKey("PopulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Population", b =>
                {
                    b.Navigation("PopulationRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
